package com.mrsisa.tim22.model;

public enum Amenity {
    WIFI, FIRST_AID_KIT, FISHING_POLES, FISHING_NET, SONAR, GPS, KITCHEN, AC, POOL, GYM, PET_FRIENDLY, PARKING, FRIDGE, HEATING, WASHER, TV, BBQ,
}
